@Echo off
title GoAniWayneNathaniel2600 Version Checker
echo GAWN2600 Pro
echo Version 25H2 (Build 26052.ge_release.250226-0730, 26052.1000)
echo Full buildtag: 26052.1000.ge_release.250226-0730
echo:
echo New Features and Changes
echo:
echo 1. Added New Assets
echo:
echo 2. The Exclusive Custom Poses, which were introduced since build 22533, has been removed.
echo:
echo 3. The Links related to the old GAWN2600 branding has been temporarily removed.
echo:
pause
cls
echo Bug Fixes.
echo:
echo No bugfixes were included in this build.
echo:
pause